# .github/workflows/publish.yml

# Workflow name
name: "Publish"

# Events for the workflow
on:
  push:
    branches:
      - main

# List of jobs
jobs:
  npm-publish:
    # Operating System
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    # Job steps
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0 # To get all tags
          token: ${{ secrets.BOT_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Build Storybook
        run: npm run build-storybook
      - name: Deploy Storybook
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: gh-pages
          folder: storybook-static
      - name: Bump patch version
        run: npm version patch
      - name: Publish to GitHub
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[skip ci] Publish new patch version"
          push_options: --force
        # commit the latest version
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
